options:
  check_dns:
    default: true
    description: Check if peers are resolveble
    type: boolean
  check_local_hostname:
    default: true
    description: Check if local hostname is resolvable
    type: boolean
  dns_server:
    default: ''
    description: Use unit default DNS server 
    type: string
  dns_tries:
    default: 1
    description: Number of DNS resolution attempts per query
    type: int
  dns_time:
    default: 3
    description: Timeout in seconds per DNS query try
    type: int
  ping_timeout:
    default: 2
    description: Timeout in seconds per ICMP request
    type: int
  ping_tries:
    default: 1
    description: Number of ICMP packets per ping
    type: int
  supress_status:
    default: False
    description: Enable this if you intend to consume this layer - supresses status messages
    type: boolean
  required_mtu:
    default: 0
    description: Desired MTU for all nodes - block if the unit MTU is different (accounting for encapsulation). 0 disables.
    type: int
  min_speed:
    default: 0
    description: Minimum transfer speed in mbit/s required to pass the test. 0 disables.
    type: int
